### ISSUE TITLE
Enums SubbreditsWhere need to end with .json if using anonymous session

### ISSUE THREAD

**Issue by shusain93** [sonsongithub/reddift#185]
You'll get a JSON serializer error because without .json it returns the [HTML](https://www.reddit.com/subreddits/default) version instead of the [json](https://www.reddit.com/subreddits/default.json) version

**Comment by sonsongithub** [comment]
Fixed it.
78ef00905a8f4178044a90581826c8381d3d6b1c
I'll later merge develop to master.
