### ISSUE TITLE
Upgrade to swift 3 and iOS 10 APIs

### ISSUE THREAD

**Issue by shusain93** [sonsongithub/reddift#188]
Yeah this is going to be painful.. Trying to port my reddift project by hand is turning out to be a entirely frighteningly bad mess. Thank god for version control though. I know you'll likely have zero time however I'm just adding an issue here for future reference so that eventually someone else can try and pick this up.

I'm slowly chugging through this however I'm using a modified code base because I made some bug fixes decided (probably a bad idea at this point) to not commit them or pull new changes from git which could make this merge incompatible. Comand-Option-Control-F is your friend here (fix all issues in scope!)

**Comment by sonsongithub** [comment]
I've already been your friend....
Muuuuuuu.

**Comment by shusain93** [comment]
...what? I've finished my required changes however I'm not sure how to commit since I'm using pods not a fork.
