### ISSUE TITLE
Rename reddift_config.json.sample to reddift_config.json

### ISSUE THREAD

**Issue by faisalrasbihan** [sonsongithub/reddift#189]
Where can I find this "reddift_config.json.sample"? I don't find this file anywhere in your repo. Do I create a new file named "reddift_config.json" and then import it to xcode project?

**Comment by sonsongithub** [comment]
It's in `/reddiftSample/reddift_config.json.sample`. https://github.com/sonsongithub/reddift/blob/master/reddiftSample/reddift_config.json.sample

You must add `reddift_config.json` into your original project.
