### ISSUE TITLE
Quick question..

### ISSUE THREAD

**Issue by AndreAbdel27** [sonsongithub/reddift#193]
how can I filter the Links gotten from session?.getList(subreddit)
I'm getting around 27 links per call, and I only need 10 top
I'm assuming it has to do something with the Paginator().

anyone can give me a hand?

**Comment by AndreAbdel27** [comment]
Quickest solution? read the documentation.... Ik.

**Comment by sonsongithub** [comment]
Use ```limit``` parameter.
