### ISSUE TITLE
Login Bad Request

### ISSUE THREAD

**Issue by DsrMedia** [sonsongithub/reddift#197]
Hi, so first of all it was a huge pain to get the project to even compile. The instructions are unclear, there were compile errors, dependencies needed to be added manually into subfolders. It finally runs though, now when I try to add an account and add my credentials and hit login in the browser it says "bad request (reddit.com) you sent an invalid request" and it doesn't redirect back to the app. Please provide proper instructions on how to set everything up, otherwise this is a huge waste of time.

**Comment by sonsongithub** [comment]
Fixed up problems of submodules.

> "bad request (reddit.com) you sent an invalid request"

You have to set up and get client ID and redirect URI.
Check README.md.

**Comment by DsrMedia** [comment]
Thanks for fixing it, I will try it later. I have fixed the bad request issue.
